version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: novelweb
      MYSQL_USER: user
      MYSQL_PASSWORD: User@1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # Lưu trữ dữ liệu lâu dài
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql # Import dữ liệu


  novel-web-frontend:
    build: ../novel-web-frontend
    ports:
      - "4200:80"
    networks:
      - microservice-network


  novel-web-backend:
    build: ../novel-web-backend
    ports:
      - "8080:8080"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
